//! Generated Verilog testbench harness for event-driven simulators
//! (Icarus / VCS / Vivado xsim).
//!
//! Implements the same stdin/stdout line protocol as the Verilator C++
//! harness (`set PORT HEX` / `get PORT` / `eval` / `finish`), so `Dut`
//! works unchanged:
//!
//! - stdin is file descriptor 32'h8000_0000 (the Verilog-2001 convention
//!   followed by Icarus and VCS; xsim in `-R` batch mode is expected to
//!   pass the process stdin through — untested, no local Vivado);
//! - `eval` (and `get`) step 1ns so scheduled deltas / nonblocking
//!   assignments settle before the response, matching the cycle-accurate
//!   "eval" semantics of the Verilator harness;
//! - ports >64 bits are rejected at generation time (the protocol carries
//!   u64 values); inout ports are left unconnected.

use super::{ModuleInfo, SimError};

const MAX_PORT_WIDTH: u32 = 64;

/// Generate `tb_<top>.v` contents.
pub fn harness_verilog(top: &ModuleInfo, trace: bool) -> Result<String, SimError> {
    let tb_name = format!("tb_{}", top.name);

    let mut decls = String::new();
    let mut conn_list: Vec<String> = Vec::new();
    for p in &top.ports {
        if p.width > MAX_PORT_WIDTH {
            return Err(SimError::BadManifest(format!(
                "port '{}' is {} bits wide; the sim protocol supports up to 64",
                p.name, p.width
            )));
        }
        let range = if p.width == 1 {
            String::new()
        } else {
            format!("[{}:0] ", p.width - 1)
        };
        match p.dir.as_str() {
            "input" => {
                decls.push_str(&format!("  reg {}{};\n", range, p.name));
                conn_list.push(format!(".{}({})", p.name, p.name));
            }
            "output" => {
                decls.push_str(&format!("  wire {}{};\n", range, p.name));
                conn_list.push(format!(".{}({})", p.name, p.name));
            }
            // Cannot be driven or read through this protocol.
            "inout" => conn_list.push(format!(".{}()", p.name)),
            other => {
                return Err(SimError::BadManifest(format!(
                    "port '{}' has unknown direction '{other}'",
                    p.name
                )))
            }
        }
    }
    let conns = conn_list.join(", ");

    let mut set_cases = String::new();
    let mut get_cases = String::new();
    for p in &top.ports {
        if p.is_drivable() {
            let slice = if p.width == 64 {
                "val".to_string()
            } else {
                format!("val[{}:0]", p.width - 1)
            };
            set_cases.push_str(&format!(
                "      if (name == \"{n}\") begin {n} = {slice}; $display(\"ok\"); end else\n",
                n = p.name,
            ));
        }
        if p.is_readable() {
            get_cases.push_str(&format!(
                "      if (name == \"{n}\") begin $display(\"%h\", {n}); end else\n",
                n = p.name,
            ));
        }
    }
    // The dispatch chains above end with a dangling `else` — close each
    // with the unknown-port branch.
    let set_chain = format!("{set_cases}      begin $display(\"ERR unknown port %0s\", name); end\n");
    let get_chain = format!("{get_cases}      begin $display(\"ERR unknown port %0s\", name); end\n");

    let dump = if trace {
        "    $dumpfile(\"wave.vcd\");\n    $dumpvars(0, dut);\n".to_string()
    } else {
        String::new()
    };

    Ok(format!(
        r#"// Auto-generated by typort sim (do not edit).
`timescale 1ns/1ps
module {tb_name};
  reg [63:0] val;
  reg [8*16-1:0] cmd;
  reg [8*64-1:0] name;
  integer code;
{decls}
  {top_name} dut ({conns});

  initial begin
{dump}    forever begin
      code = $fscanf(32'h8000_0000, "%s", cmd);
      if (code < 1) begin
        $fflush(32'h8000_0001);
        $finish;
      end
      if (cmd == "set") begin
        code = $fscanf(32'h8000_0000, "%s %h", name, val);
        if (code == 2) begin
{set_chain}        end else
          $display("ERR set args");
      end else if (cmd == "get") begin
        code = $fscanf(32'h8000_0000, "%s", name);
        #1;
{get_chain}      end else if (cmd == "eval") begin
        #1;
        $display("ok");
      end else if (cmd == "finish") begin
        $fflush(32'h8000_0001);
        $finish;
      end else begin
        $display("ERR bad cmd");
      end
      $fflush(32'h8000_0001);
    end
  end
endmodule
"#,
        tb_name = tb_name,
        top_name = top.name,
        decls = decls,
        conns = conns,
        dump = dump,
        set_chain = set_chain,
        get_chain = get_chain,
    ))
}
