//! Verilator backend (cycle-accurate C++ harness).
//!
//! Windows/MSYS2 notes (probed on Verilator 4.024 mingw64):
//! - the `verilator` perl wrapper breaks under some PATHs; prefer
//!   `verilator_bin.exe` directly;
//! - the generated .mk hardcodes an MSYS2-style `VERILATOR_ROOT`
//!   (`/mingw64/...`) that native make cannot resolve — a command-line
//!   `VERILATOR_ROOT=<windows path>` override fixes it (command-line
//!   assignments beat in-file ones);
//! - VERILATOR_ROOT must use forward slashes: the mk feeds it to perl
//!   (the verilator_includer step), and perl eats backslashes as escapes;
//! - the model link step needs the toolchain's g++/ranlib, so make runs
//!   with the verilator bin dir prepended to PATH.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

use super::runner::{BuildPlan, CompiledModel, SimulatorRunner};
use super::{find_in_path, run_tool, ModuleInfo, SimError};

/// Locate verilator. Resolution order: $VERILATOR, then `verilator_bin` on
/// PATH (the native binary — the perl wrapper breaks under some PATHs),
/// then `verilator` on PATH, then common MSYS2 locations.
pub fn find_verilator() -> Option<PathBuf> {
    if let Some(explicit) = std::env::var_os("VERILATOR") {
        let p = PathBuf::from(explicit);
        if p.is_file() {
            return Some(p);
        }
        if let Some(found) = p.to_str().and_then(find_in_path) {
            return Some(found);
        }
    }
    if let Some(p) = find_in_path("verilator_bin") {
        return Some(p);
    }
    if let Some(p) = find_in_path("verilator") {
        // The perl wrapper — usable only if it runs; prefer _bin siblings.
        if let Some(bin) = p.parent() {
            let native = bin.join(if cfg!(windows) { "verilator_bin.exe" } else { "verilator_bin" });
            if native.is_file() {
                return Some(native);
            }
        }
        return Some(p);
    }
    // Common MSYS2 install locations.
    for prefix in ["C:/msys64", "C:/msys32", "C:/tools/msys64"] {
        let p = PathBuf::from(prefix).join("mingw64/bin/verilator_bin.exe");
        if p.is_file() {
            return Some(p);
        }
    }
    None
}

/// Locate make. Prefers `mingw32-make` from the verilator toolchain dir
/// (native binary, no MSYS runtime needed).
fn find_make(verilator: &std::path::Path) -> Option<PathBuf> {
    if let Some(explicit) = std::env::var_os("MAKE") {
        let p = PathBuf::from(explicit);
        if p.is_file() {
            return Some(p);
        }
    }
    let bin = verilator.parent()?;
    let candidate = bin.join(if cfg!(windows) { "mingw32-make.exe" } else { "make" });
    if candidate.is_file() {
        return Some(candidate);
    }
    find_in_path("mingw32-make").or_else(|| find_in_path("make"))
}

/// Windows-style VERILATOR_ROOT for the verilator toolchain at `verilator`
/// (`<prefix>/share/verilator`), verified to contain verilated.mk. None when
/// the layout doesn't match (make then uses the .mk's own path).
fn verilator_root(verilator: &std::path::Path) -> Option<PathBuf> {
    let prefix = verilator.parent()?.parent()?;
    let root = prefix.join("share/verilator");
    if root.join("include/verilated.mk").is_file() {
        Some(root)
    } else {
        None
    }
}

/// Generate the C++ harness: a stdin/stdout line protocol (`set PORT HEX`
/// / `get PORT` / `eval` / `finish`) so host Rust code can drive the model
/// interactively. With `trace`, eval steps also dump VCD frames to
/// wave.vcd (requires `--trace` on the verilator run).
fn harness_cpp(top: &ModuleInfo, trace: bool) -> String {
    let mut set_cases = String::new();
    let mut get_cases = String::new();
    for p in &top.ports {
        let name = &p.name;
        set_cases.push_str(&format!(
            "        else if (!strcmp(name, \"{name}\")) dut->{name} = ({t})v;\n",
            t = p.ctype()
        ));
        get_cases.push_str(&format!(
            "        else if (!strcmp(name, \"{name}\")) printf(\"%llx\\n\", (unsigned long long)dut->{name});\n"
        ));
    }
    let (trace_include, trace_decl, trace_init, trace_dump, trace_close) = if trace {
        (
            "#include \"verilated_vcd_c.h\"\n",
            "static VerilatedVcdC* tfp = NULL;\nstatic vluint64_t sim_time = 0;\n",
            "    Verilated::traceEverOn(true);\n    tfp = new VerilatedVcdC;\n    dut->trace(tfp, 99);\n    tfp->open(\"wave.vcd\");\n",
            "            if (tfp) tfp->dump(sim_time++);\n",
            "    if (tfp) tfp->close();\n",
        )
    } else {
        ("", "", "", "", "")
    };
    format!(
        r#"// Auto-generated by typort sim (do not edit).
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "V{top_name}.h"
#include "verilated.h"
{trace_include}{trace_decl}
int main(int argc, char** argv) {{
    Verilated::commandArgs(argc, argv);
    V{top_name}* dut = new V{top_name};
{trace_init}    char line[512];
    while (fgets(line, sizeof line, stdin)) {{
        if (strncmp(line, "set ", 4) == 0) {{
            char name[128]; char hex[128];
            if (sscanf(line + 4, "%127s %127s", name, hex) != 2) {{ printf("ERR set args\n"); fflush(stdout); continue; }}
            unsigned long long v = strtoull(hex, NULL, 16);
            if (0) {{}}
{set_cases}            else {{ printf("ERR unknown port %s\n", name); fflush(stdout); continue; }}
            printf("ok\n");
        }} else if (strncmp(line, "get ", 4) == 0) {{
            char name[128];
            sscanf(line + 4, "%127s", name);
            if (0) {{}}
{get_cases}            else printf("ERR unknown port %s\n", name);
        }} else if (strncmp(line, "eval", 4) == 0) {{
            dut->eval();
{trace_dump}            printf("ok\n");
        }} else if (strncmp(line, "finish", 6) == 0) {{
            break;
        }} else {{
            printf("ERR bad cmd\n");
        }}
        fflush(stdout);
    }}
    dut->final();
{trace_close}    delete dut;
    return 0;
}}
"#,
        top_name = top.name,
        set_cases = set_cases,
        get_cases = get_cases,
        trace_include = trace_include,
        trace_decl = trace_decl,
        trace_init = trace_init,
        trace_dump = trace_dump,
        trace_close = trace_close,
    )
}

pub struct Verilator;

impl SimulatorRunner for Verilator {
    fn name(&self) -> &'static str {
        "verilator"
    }

    fn find_tool(&self) -> Option<PathBuf> {
        find_verilator()
    }

    fn build(&self, plan: &BuildPlan) -> Result<CompiledModel, SimError> {
        let top_name = &plan.top_name;
        let top_info = plan
            .manifest
            .top_module()
            .ok_or_else(|| SimError::BadManifest(format!("top module '{top_name}' missing from manifest")))?
            .clone();

        let verilator = find_verilator().ok_or_else(|| {
            SimError::ToolMissing("verilator not found (set VERILATOR or install MSYS2/mingw64 verilator)".into())
        })?;
        let make = find_make(&verilator).ok_or_else(|| {
            SimError::ToolMissing("make not found (mingw32-make or make on PATH, or set MAKE)".into())
        })?;

        fs::write(plan.workdir.join("harness.cpp"), harness_cpp(&top_info, plan.trace))?;

        let objdir = plan.workdir.join(format!("obj_{top_name}"));
        let model_name = "top_model";

        // 1. verilator: generate C++ + makefile. File arguments are passed
        //    RELATIVE with cwd=workdir: verilator_bin misparses absolute
        //    Windows paths (treats them as module names to -y-search).
        let mut vcmd = Command::new(&verilator);
        vcmd
            .current_dir(&plan.workdir)
            .args(["--cc", "--exe", "-Wno-fatal"])
            .arg("--top-module").arg(top_name)
            .arg("-Mdir").arg(format!("obj_{top_name}"))
            .arg("-o").arg(model_name)
            .args(&plan.extra_args);
        if plan.trace {
            vcmd.arg("--trace");
        }
        vcmd.arg("harness.cpp").arg(format!("{top_name}.v"));
        run_tool(&mut vcmd, "verilator")?;

        // 2. make: build the model (run inside the obj dir, like the
        //    verified probe / verify.py invocation). VERILATOR_ROOT is
        //    passed as a command-line override (the generated .mk
        //    hardcodes an MSYS2-style path native make cannot read) and
        //    the toolchain bin dir is prepended to PATH so g++/ranlib
        //    resolve.
        let mut mcmd = Command::new(&make);
        mcmd
            .current_dir(&objdir)
            .arg("-f")
            .arg(format!("V{top_name}.mk"));
        if let Some(root) = verilator_root(&verilator) {
            let root = root.display().to_string().replace('\\', "/");
            mcmd.arg(format!("VERILATOR_ROOT={root}"));
        }
        let old_path = std::env::var_os("PATH").unwrap_or_default();
        if let Some(bin) = verilator.parent() {
            mcmd.env(
                "PATH",
                std::env::join_paths(std::iter::once(bin.to_path_buf()).chain(std::env::split_paths(&old_path)))
                    .unwrap_or(old_path.clone()),
            );
        }
        run_tool(&mut mcmd, "make")?;

        let exe = objdir.join(if cfg!(windows) {
            format!("{model_name}.exe")
        } else {
            model_name.to_string()
        });
        if !exe.is_file() {
            return Err(SimError::CommandFailed {
                tool: "make".into(),
                output: format!("model binary not produced at {}", exe.display()),
            });
        }
        Ok(CompiledModel {
            exe,
            exe_args: Vec::new(),
            workdir: plan.workdir.clone(),
            manifest: plan.manifest.clone(),
        })
    }
}
